server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://root:CLhwlfRZQmOFOBSoZiWCPMUFemqubUAL@tramway.proxy.rlwy.net:47808/railway
    username: root
    password: CLhwlfRZQmOFOBSoZiWCPMUFemqubUAL

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
