server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org:
      springframework:
        web:
          socket=DEBUG:
        messaging=DEBUG: